apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operators
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  project: default
  source:
    path: operators/
    repoURL: https://github.com/tonykhbo/base-argo-helm-app.git
    targetRevision: HEAD